#!/bin/sh

export PATH=$PATH:$(realpath ..)/toolchain/bin
export KBUILD_OUTPUT=out
export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
export INSTALL_MOD_PATH=ko
export INSTALL_MOD_STRIP=1

make KERNELDIR=$(realpath ..)/kernel
# ${CROSS_COMPILE}strip  --strip-debug drv_wlan/MT6632/wlan/wlan_mt76x8_sdio.ko